### ISSUE TITLE
Feature Request - Custom Host Address Support for OpenAI

### ISSUE THREAD

**Issue by VergilWu** [franciscopower/GPTerminal#16]
### Overview
I propose adding support for custom host addresses in the OpenAI API. This feature would allow users to specify their own host address for API calls, providing greater flexibility and control.

### Goal
The goal is to enable users to connect to OpenAI API using a custom host address, allowing integration with custom infrastructure setups or proxy servers.

### Proposed Solution
Introduce a configuration option or environment variable that allows users to specify a custom host address for OpenAI API calls. This would provide the flexibility to route requests through user-defined servers or alternative network setups.

### Benefits
- Seamless integration into various deployment scenarios
- Enhanced control over network configurations
- Better adaptability to specific security requirements or on-premises deployments
Implementing this feature would empower developers to tailor the OpenAI API integration to their specific needs, improving the overall user experience.

**Comment by franciscopower** [comment]
Great idea, I'm going to do it!

**Comment by franciscopower** [comment]
I've completed this feature. I added an env variable called GPTERMINAL_LLM_API_HOST that you can set to the host address you desire. If it is not set, it defaults to the OpenAI API host address. 
I also added an env variable to allow you to choose the model that OpenAI is using, but by default it will be gpt-3.5-turbo.
Check out more details and the latest binaries in the releases page, [release 0.2.0](https://github.com/franciscopower/GPTerminal/releases/tag/0.2.0)

**Comment by VergilWu** [comment]
I appreciate your hard work in completing this feature.
: )
